# Configuration for MPC Aggregator

server:
  port: "8080"
  name: "MPC Node"
  enable_mtls: true
  server_cert_path: "/run/secrets/server.crt"
  server_key_path: "/run/secrets/server.key"
  ca_cert_path: "/run/secrets/ca.crt"

zkp:
  key_path: "keys/verifying.key"
  max_limit: 10000

aggregator:
  expected_meters: 10
  node_id: 0
  output_path: "/dev/shm/mp-spdz"
  scale_factor: 1000.0

# Map client certificate CommonName (CN) to NodeID.
client_cn_map:
  SimulatorClient: 0  # <--- Dodaj ovo, ovo je ime iz nase bash skripte
  mpc-client-node0: 0
  mpc-client-node1: 1
  mpc-client-node2: 2
