version: '3.8'

services:
  # --- SERVER A (Node 0) ---
  server-a:
    build:
      context: ./mpc-aggregator
    container_name: server-a
    ports:
      - "8080:8443"
    environment:
      - NODE_ID=0
      - PORT=8080
    volumes:
      - ./certs:/run/secrets:ro # Promenjeno u ./certs gde su tvoji rucni fajlovi
      - ./config.yaml:/app/config.yaml:ro
    networks:
      - mpc-network
    # Ceka tvoj server.crt
    command: ["/bin/sh", "-c", "while [ ! -f /run/secrets/server.crt ]; do echo '[WAIT] waiting for TLS certs'; sleep 1; done; exec ./mpc-server"]

  mpc-node-a:
    build:
      context: ./mpc-engine
      args:
        NUM_METERS: ${NUM_METERS:-10}
        NUM_PARTIES: ${NUM_PARTIES:-3}
    container_name: mpc-node-a
    environment:
      - NODE_ID=0
    volumes:
      - ./certs:/run/secrets:ro
    depends_on:
      - server-a
    networks:
      - mpc-network
    # Ceka client.crt
    entrypoint: ["/bin/sh", "-c", "while [ ! -f /run/secrets/client.crt ]; do echo '[WAIT] waiting for client cert'; sleep 1; done; exec ./entrypoint.sh"]
    ports:
      - "9000:9000"
    tmpfs:
      - /tmp

  # --- SERVER B (Node 1) ---
  server-b:
    build:
      context: ./mpc-aggregator
    container_name: server-b
    ports:
      - "8081:8443"
    environment:
      - NODE_ID=1
      - PORT=8080
    volumes:
      - ./certs:/run/secrets:ro
      - ./config.yaml:/app/config.yaml:ro
    networks:
      - mpc-network
    command: ["/bin/sh", "-c", "while [ ! -f /run/secrets/server.crt ]; do echo '[WAIT] waiting for TLS certs'; sleep 1; done; exec ./mpc-server"]

  mpc-node-b:
    build:
      context: ./mpc-engine
    container_name: mpc-node-b
    environment:
      - NODE_ID=1
    volumes:
      - ./certs:/run/secrets:ro
    depends_on:
      - server-b
    networks:
      - mpc-network
    entrypoint: ["/bin/sh", "-c", "while [ ! -f /run/secrets/client.crt ]; do echo '[WAIT] waiting for client cert'; sleep 1; done; exec ./entrypoint.sh"]
    ports:
      - "9001:9000"
    tmpfs:
      - /tmp

  # --- SERVER C (Node 2) ---
  server-c:
    build:
      context: ./mpc-aggregator
    container_name: server-c
    ports:
      - "8082:8443"
    environment:
      - NODE_ID=2
      - PORT=8080
    volumes:
      - ./certs:/run/secrets:ro
      - ./config.yaml:/app/config.yaml:ro
    networks:
      - mpc-network
    command: ["/bin/sh", "-c", "while [ ! -f /run/secrets/server.crt ]; do echo '[WAIT] waiting for TLS certs'; sleep 1; done; exec ./mpc-server"]

  mpc-node-c:
    build:
      context: ./mpc-engine
    container_name: mpc-node-c
    environment:
      - NODE_ID=2
    volumes:
      - ./certs:/run/secrets:ro
    depends_on:
      - server-c
    networks:
      - mpc-network
    entrypoint: ["/bin/sh", "-c", "while [ ! -f /run/secrets/client.crt ]; do echo '[WAIT] waiting for client cert'; sleep 1; done; exec ./entrypoint.sh"]
    ports:
      - "9002:9000"
    tmpfs:
      - /tmp

networks:
  mpc-network:
    driver: bridge