version: '3.8'

services:
  # --- SERVER A (Node 0) ---
  server-a:
    build:
      context: ./mpc-aggregator
      dockerfile: Dockerfile
    container_name: server-a
    ports:
      - "8080:8080"
    environment:
      - NODE_ID=0
      - PORT=8080
    networks:
      - mpc-network

  mpc-node-a:
    build:
      context: ./mpc-engine
      dockerfile: Dockerfile
      args:
        NUM_METERS: ${NUM_METERS:-10}
        NUM_PARTIES: ${NUM_PARTIES:-3}
    container_name: mpc-node-a
    environment:
      - NODE_ID=0
    depends_on:
      - server-a
    networks:
      - mpc-network
    ports:
      - "9000:9000"   # TCP receiver
    expose:
      - "5000"
      - "5001"
      - "5002"
    tmpfs:
      - /tmp

  # --- SERVER B (Node 1) ---
  server-b:
    build:
      context: ./mpc-aggregator
      dockerfile: Dockerfile
    container_name: server-b
    ports:
      - "8081:8080"
    environment:
      - NODE_ID=1
      - PORT=8080
    networks:
      - mpc-network

  mpc-node-b:
    build:
      context: ./mpc-engine
      dockerfile: Dockerfile
      args:
        NUM_METERS: ${NUM_METERS:-10}
        NUM_PARTIES: ${NUM_PARTIES:-3}
    container_name: mpc-node-b
    environment:
      - NODE_ID=1
    depends_on:
      - server-b
    networks:
      - mpc-network
    ports:
      - "9001:9000"
    expose:
      - "5000"
      - "5001"
      - "5002"
    tmpfs:
      - /tmp   # <--- DODATO

  # --- SERVER C (Node 2) ---
  server-c:
    build:
      context: ./mpc-aggregator
      dockerfile: Dockerfile
    container_name: server-c
    ports:
      - "8082:8080"
    environment:
      - NODE_ID=2
      - PORT=8080
    networks:
      - mpc-network

  mpc-node-c:
    build:
      context: ./mpc-engine
      dockerfile: Dockerfile
      args:
        NUM_METERS: ${NUM_METERS:-10}
        NUM_PARTIES: ${NUM_PARTIES:-3}
    container_name: mpc-node-c
    environment:
      - NODE_ID=2
    depends_on:
      - server-c
    networks:
      - mpc-network
    ports:
      - "9002:9000"
    expose:
      - "5000"
      - "5001"
      - "5002"
    tmpfs:
      - /tmp

networks:
  mpc-network:
    driver: bridge